# Generated by Django 3.1 on 2020-08-25 23:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementsStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('the_geom_webmercator', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('created_at', models.CharField(max_length=30)),
                ('updated_at', models.CharField(max_length=30)),
                ('measure_type', models.CharField(max_length=10)),
                ('measure', models.FloatField()),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
            ],
        ),
    ]
