# Generated by Django 3.1 on 2020-08-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementsstatistics',
            name='population',
            field=models.FloatField(null=True),
        ),
    ]
